// @ts-nocheck
export class Gig {
    id: string;
    name: string;
    impressions: number;
    clicks: number;
    orders: number;
    cancellations: number;
    status: string;
    user_name: string;
    user_username: string;
    rating: number;
    price: number;
    my_gig: boolean;
    image: string;
    user_image: string;
    desc: string;
    gig_category: string;
    gig_description: string;
    gig_genres: string;
    gig_purposes: string;
    user_from: string;
    user_registration: string;
    user_desc: string;
    gig_faq: string;
    gig_reviews_1: number;
    gig_reviews_2: number;
    gig_reviews_3: number;
    gig_reviews_4: number;
    gig_reviews_5: number;
    gig_reviews_all: number;
  }